[package]
name = "neurust"
version = "0.1.2"
authors = ["Marcin Szulc <m.szulc2@protonmail.com>"]
edition = "2018"

[dependencies]
num = "0.3"
openblas-src = { version = "0.9.0", default-features = false, features = ["cblas", "system"] }
cblas-sys = "0.1"